# Generated by Django 4.0 on 2021-12-28 13:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecom_user_profile',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('phone_number', models.IntegerField(default=0)),
                ('country_code', models.IntegerField(default=0)),
                ('email', models.EmailField(default='', max_length=254)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('avatar', models.ImageField(default='', upload_to='shop/user_images')),
                ('gender', models.CharField(max_length=10)),
                ('aadhar_uid', models.IntegerField()),
                ('verification_status', models.CharField(default='unverified', max_length=20)),
                ('date_joined', models.DateTimeField()),
                ('date_verified', models.DateTimeField(default=datetime.datetime(2021, 12, 28, 13, 24, 41, 606846))),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('product_name', models.CharField(max_length=50)),
                ('product_desription', models.TextField()),
                ('publish_date', models.DateTimeField()),
                ('product_category', models.CharField(max_length=40)),
                ('product_price', models.IntegerField(default=0)),
                ('product_image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
        migrations.CreateModel(
            name='Ecom_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=16)),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ecom_user_profile')),
            ],
        ),
    ]
