# Generated by Django 4.0 on 2021-12-29 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecom_user_profile',
            name='aadhar_uid',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='ecom_user_profile',
            name='date_verified',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 29, 8, 47, 12, 760703)),
        ),
    ]
