# Generated by Django 4.0 on 2021-12-29 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_ecom_user_profile_date_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecom_user_profile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 29, 8, 55, 23, 949209)),
        ),
        migrations.AlterField(
            model_name='ecom_user_profile',
            name='date_verified',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 29, 8, 55, 23, 949220)),
        ),
    ]
